name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc lcov libncurses5-dev

    - name: Build project
      run: |
        make test

    - name: Run tests
      run: |
        ./companders_fulltest

    - name: Capture coverage info
      run: |
        lcov --directory . --capture --output-file coverage.info
   
    - name: Filter out system and test code
      run: |
        lcov --remove coverage.info 'tests/*' '/usr/*' 'companders_fulltest*' --output-file coverage.info

    - name: List coverage info
      run: |
        lcov --list coverage.info

